### ISSUE TITLE
Bad description of functionality

### ISSUE THREAD

**Issue by niblius** [venables/koa-json-body#4]
Description states the following "If there is a JSON parsing error, the middleware will set ctx.request.body to {} and continue."

But the library doesn't actually set ctx.request.body to an empty object. ctx.request.body stays undefined. Therefore if later you use ctx.request.body.login, you will get an exception "TypeError: Cannot read property 'login' of undefined" instead of silently getting undefined.

**Comment by venables** [comment]
Thanks @niblius -- I just updated the README for a better description, and have updated the test suite to match it. I will be releasing an updated version to npm shortly.
